Python/hello_django/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'


urlpatterns = [
    path('<int:post_id>/', views.post, name='post'),
    path('', views.blog, name='home'),
    path('exemplo/', views.exemplo, name='exemplo'),
]

Python/hello_django/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')

]

Python/hello_django/project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

Python/hello_django/blog/models.py
from django.db import models

# Create your models here.

Python/hello_django/home/models.py
from django.db import models

# Create your models here.

Python/hello_django/blog/views.py
# from django.http import HttpResponse
from django.shortcuts import render
from blog.data import posts
from typing import Any
from django.http import HttpRequest, Http404


def blog(request):
    print('blog')

    context = {
        # 'text': 'Olá blog',
        'posts': posts
    }
    return render(
        request,
        'blog/index.html',
        context,
    )


def exemplo(request):

    context = {
        'text': 'Olá exemplo ',
    }
    
    print('exemplo')
    return render(
        request,
        'blog/exemplo.html',
        context,
    )


def post(request: HttpRequest, post_id: int):
    print('post', id)
    found_post: dict[str, Any] | None = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break

    if found_post is None:
        raise Http404('Post não existe.')

    context = {
        # 'text': 'Olá post',
        'post': found_post,
        'title': found_post['title'] + ' - ',
    }

    return render(
        request,
        'blog/post.html',
        context,
    )

Python/hello_django/home/views.py
from django.shortcuts import render


def home(request):

    context = {
        'text': 'Olá home'
    }

    print('HOME')
    # RENDER ---> busca arquivos dos diretórios: TEMPLATES e BASE
    return render(
        request,
        'home/index.html',  # Busca automaticamente todos os arquivos que estão dentro da pasta TEMPLATES na raiz da pasta do APP
        context,
    )

Python/hello_django/blog/templates/blog/exemplo.html
{% extends "global/base.html" %}
{% block texto %} {{text}} {% endblock texto %}

Python/hello_django/blog/templates/blog/index.html
{% extends "global/base.html" %}
{% block texto %} {{text}} {% endblock texto %}


{% block posts %} 
    {% for post in posts%}
        {% include "global/partials/postblock.html"%}
    {% endfor %}
{% endblock posts %}
 

Python/hello_django/blog/templates/blog/post.html
{% extends "global/base.html" %}
{% block texto %} {{text}} {% endblock texto %}


{% block posts %} 
    <article class="post single-post">
        <header>
            <h1 class="post__title">
                <a href="{% url "blog:post" post.id %}">
                {{ post.title }}
                </a>
            </h1>
        </header>
        <div class="post__body">
            {{ post.body }}
        </div>
    </article>
{% endblock posts %}
 

Python/hello_django/home/templates/home/index.html
{% extends "global/base.html" %}
 
{% block texto %}
    {{ text }}
{% endblock texto %}

{% block home %} 
    <h1>HOME</h1>
{% endblock home %}
 